version: '3.8'
services:
  fastapi:
    build: ./fastapi_app
    container_name: fastapi_app
    ports:
      - "8001:8000"
  flask1:
    build: ./flask_app1
    container_name: flask_app1
    ports:
      - "5001:5000"
  flask2:
    build: ./flask_app2
    container_name: flask_app2
    ports:
      - "5002:5000"
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - fastapi
      - flask1
      - flask2
